categories: [Proteomics]
description: BiblioSpec Spectral Library Tools
long_description: |
  BiblioSpec is a suite of software tools for creating and searching
  MS/MS peptide spectrum libraries.
name: bibliospec
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/bibliospec
type: unrestricted

