owner: galaxyp
name: feature_alignment
categories:
- Proteomics
description: Feature Alignment of peakgroups below a FDR
long_description: |
 TRIC uses a graph-based alignment strategy based on non-linear retention time correction to integrate information from all available runs.

  https://github.com/msproteomicstools/msproteomicstools
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/feature_alignment
type: unrestricted
