categories: [Proteomics]
description: Graph2Pro-var package
long_description: |
    This is the Galaxy Wrapper for the Graph2Pro-var
    
name: graph2provar
owner: galaxyp
homepage_url: https://github.com/COL-IU/graph2pro-var
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/graph2provar
