name: pdb2pqr
owner: galaxyp
description: PDB2PQR prepares PDB strucutres for biomolecular solvation/electrostatics analyses
homepage_url: http://www.poissonboltzmann.org/
long_description:
  PDB2PQR automates many of the common tasks of preparing structures for continuum solvation calculations 
  as well as many other types of biomolecular structure modeling, analysis, and simulation. 
  These tasks include
    - adding a limited number of missing heavy (non-hydrogen) atoms to biomolecular structures,
    - estimating titration states and protonating biomolecules in a manner consistent with favorable hydrogen bonding,
    - assigning charge and radius parameters from a variety of force fields, and
    - generating PQR output compatible with several popular computational biology modeling and analysis packages.

  http://www.poissonboltzmann.org/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pdb2pqr
type: unrestricted
categories:
  - Proteomics
